### ISSUE TITLE
US 0.2 - Register y Login

### ISSUE THREAD

**Issue by Brynfox** [pgPilfs/pil-money-g4a-pil-grupo1-aula4#26]
Como usuario quiero abrir una cuenta en la billetera digital para hacer uso de la plataforma.

#44 Esta tarea corresponde a esta US.
#45 Esta tarea corresponde a esta US.
#46 Esta tarea corresponde a esta US.
#47 Esta tarea corresponde a esta US.
#48 Esta tarea corresponde a esta US.
#49 Esta tarea corresponde a esta US.
#50 Esta tarea corresponde a esta US.
#51 Esta tarea corresponde a esta US.
#52 Esta tarea corresponde a esta US.
#53 Esta tarea corresponde a esta US.
#54 Esta tarea corresponde a esta US.
#55 Esta tarea corresponde a esta US.
#56 Esta tarea corresponde a esta US.
#57 Esta tarea corresponde a esta US.
#58 Esta tarea corresponde a esta US.
#59 Esta tarea corresponde a esta US.
#60 Esta tarea corresponde a esta US.
#61 Esta tarea corresponde a esta US.
#62 Esta tarea corresponde a esta US.
#63 Esta tarea corresponde a esta US.
#64 Esta tarea corresponde a esta US.
#65 Esta tarea corresponde a esta US.
#66 Esta tarea corresponde a esta US.
#67 Esta tarea corresponde a esta US.
#68 Esta tarea corresponde a esta US.
#85 Esta tarea corresponde a esta US.

**Comment by carlapalmieri** [comment]
Necesitamos 
-Un header
-Un footer
-Nombre de la billetera
-Logo

**Comment by carlapalmieri** [comment]
El diseño debe ser responsive (tanto para el login como para el registro)
